version: '3.8'

services:
  test-browser:
    image: selenium/standalone-chrome:latest
    ports:
      - "4444:4444"
      - "7900:7900"
    environment:
      - SE_VNC_NO_PASSWORD=1
    extra_hosts:
      - "localhost:127.0.0.2"  # Block localhost
      - "host.docker.internal:127.0.0.2"  # Block host machine
    
  # Access the browser at http://localhost:7900
  # Then navigate to https://blockaipuremm.ngrok.dev
  # This simulates a completely external user