#!/bin/bash

echo "Setting up ngrok tunnels for BlockAI Pure MM..."
echo ""
echo "You need to run ngrok with both frontend and backend ports."
echo ""
echo "Option 1: If you have ngrok configured with a config file:"
echo "  ngrok start blockai-frontend blockai-backend"
echo ""
echo "Option 2: Run these commands in separate terminals:"
echo "  Terminal 1: ngrok http 5173 --domain=blockaipuremm.ngrok.dev"
echo "  Terminal 2: ngrok http 5001"
echo ""
echo "After starting ngrok for port 5001, you'll get a URL like:"
echo "  https://abc123.ngrok-free.app"
echo ""
echo "Then update the .env file with:"
echo "  VITE_API_URL=https://abc123.ngrok-free.app/api"
echo ""
echo "And restart the frontend server (npm run dev)"